FROM node:14

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json", "./"]

RUN npm i

COPY [".", "."]

ARG EXP_CACHE
ARG EXP_TOKEN
ARG JWT_SECRET
ARG JWT_SECRET_REFRESH
ARG MONGODB_URI
ARG PORT

ENV MONGODB_URI=$MONGODB_URI
ENV EXP_TOKEN=$EXP_TOKEN
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_SECRET_REFRESH=$JWT_SECRET_REFRESH
ENV MONGODB_URI=$MONGODB_URI
ENV PORT=$PORT

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]