name: petgram-backend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Run install
      run: npm ci
    - name: Run build
      run: npm run build  
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.GIT_USER }}/petgram-backend/petgram-backend
        registry: docker.pkg.github.com
        username: ${{ secrets.GIT_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
      env:
        EXP_CACHE: ${{ secrets.EXP_CACHE }}
        EXP_TOKEN: ${{ secrets.EXP_TOKEN }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_SECRET_REFRESH: ${{ secrets.JWT_SECRET_REFRESH }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        PORT: ${{ secrets.PORT  }}